userProfileIcon=#menuUserLink
userNameLabelField=input[name='usernameRegisterPage']
emailLabelField=input[name='emailRegisterPage']
passwordLabelField=input[name='passwordRegisterPage']
confirmPasswordLabelField=input[name='confirm_passwordRegisterPage']
firstNameLabelField=input[name='first_nameRegisterPage']
lastNameLabelField=input[name='last_nameRegisterPage']
phoneNumberLabelField=input[name='phone_numberRegisterPage']
countrydropdown=select[name='countryListboxRegisterPage']
cityLabelField=input[name='cityRegisterPage']
addressLabelField=input[name='addressRegisterPage']
stateLabelField=input[name='state_/_province_/_regionRegisterPage']
postalCodeLabelField=input[name='postal_codeRegisterPage']
allowOffersCheckbox=input[name='allowOffersPromotion']
iAgreeCheckbox=input[name='i_agree']
username=input[name='username']
password=input[name='password']
productsLabel=label[id*=Link]
productName=.shop_now
itemName=.categoryRight > ul > li
itemPrice=.productPrice
categoryTitle=.categoryTitle
categoryTile=.categoryRight > ul
