people=a[href$=basic_guest_nav_menu_people]
peopletext=h1[class~=main-title]
usernameTextBox=#username
passwordTextBox=#password
submitButton=button[type='submit']
passworderror=#error-for-password
headerSignButton=a[href*=header-signin]
jobsearch=a[href*='jobs']
globalJobSearch=.global-nav__primary-item
skillsKeyword=.jobs-search-global-typeahead__input
skillsResults=div[class*='results--with-recent']
searchResultsHeader=.jobs-search-results-list__header
searchResultsCountText=.jobs-search-results-list__subtitle > span
searchResultsSection=.jobs-search-results-list__header + div
searchTotalResults=.jobs-search-results-list__header + div > ul > li
paginationSection=.artdeco-pagination__pages